name: Release

# trigger a release:
# minor:
# npm version minor -m "Release %s" && git push --tags
# patch:
# npm version patch -m "Release %s" && git push --tags

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '[0-9]+.[0-9]+.[0-9]+' # Push events to any matching semantic tag. For example, 1.10.1 or 2.0.0.
        # For more details, see https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
        # and https://docs.npmjs.com/about-semantic-versioning

jobs:
  release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/

      # set the package version to the release tag version
      - name: Check package version
        uses: technote-space/package-version-check-action@v1
        with:
          COMMIT_DISABLED: 1

      # build library
      - name: npm ci and npm run build
        run: |
          npm ci
          npm run build:prod
      - name: lint
      - run: npm run lint
      - name: unit tests
      - run: npm run test-headless

      # build demo
      - name: build demo
        run: npm run build:demo

      # deploy demo to gh-pages
      - name: deploy demo to gh-pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist/ngx-three-demo

      # build the changelog
      - name: build changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # create a github release
      - name: create release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{steps.build_changelog.outputs.changelog}}
          draft: false
          prerelease: false

      # publish to npm
      - name: publish to npm
      - run: npm run package
      - run: cd ./dist/ngx-three && npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
